### ISSUE TITLE
Typo in policy.md

### ISSUE THREAD

**Issue by AhmadHoghooghi** [zerocracy/zerocracy.github.io#10]
In [policy.md](https://github.com/zerocracy/zerocracy.github.io/blob/9f41d7bd140a4f315c60546042736ca349fbe629/pages/policy.md) - [Privacy](https://github.com/zerocracy/zerocracy.github.io/blob/master/pages/terms.md#privacy):

> We collect a **lof** of information about you

We collect a **lot** of information about you

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@ahmadhoghooghi[/z](https://www.0crat.com/u/ahmadhoghooghi) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@AhmadHoghooghi fixed, thanks

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
