### ISSUE TITLE
Re-work job limit for QA

### ISSUE THREAD

**Issue by sereshqua** [zerocracy/zerocracy.github.io#109]
Currently the policy says:

> §3 “Election.” Zerocrat may assign a job to you according to its own election rules, if you have DEV role and are not on vacation. You will be notified in job’s ticket. The rules include, in order of importance:
> 
> The highest reputation wins;
> No jobs will be assigned if reputation is below -128;
> Lowest project rate wins;
> Shortest average job completion time wins;
> The emptiest agenda wins;
> The maximum allowed size of agenda depends on your reputation:
> 3 jobs if less than +512 points,
> 8 if less than +2048,
> 16 if less than +4096,
> 24 otherwise;

I suggest that job limits for QA role should be re-worked. I don't mind having 24 jobs in my agenda not to delay programmers to receive their deserved money. 

Now, I am only allowed to have 3 jobs due to having less than 512 and I am simple not being assigned by 0crat to more.

If this policy update would be approved - then issue in farm repository can be created to do it programmatically. 

I would suggest to make these 2 ways:

1)

> 8 jobs if less than +512 points,
> 16 if less than +2048 points,
> 24 if less than +otherwise,

2) remove all limits for already GRADUATED users with QA role (like me).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@sereshqua maybe it's not very clear, but it's not related to QA: "Zerocrat may assign a job to you according to its own election rules" the job can be assigned only to performer (DEV or REV) in terms of Zerocracy, QA is not a performer but a "job reviewer". So election rules doesn't work for QA

**Comment by sereshqua** [comment]
@g4s8 got it

**Comment by 0crat** [comment]
Job `gh:zerocracy/zerocracy.github.io#109` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
