### ISSUE TITLE
Error when trying to pay $16 entrance fee

### ISSUE THREAD

**Issue by alayor** [zerocracy/zerocracy.github.io#12]
URL: https://www.0crat.com/rfp-pay
<img width="1419" alt="screen shot 2018-04-15 at 8 51 22 pm" src="https://user-images.githubusercontent.com/2164371/38788036-c7390f90-40ee-11e8-9678-b836336c5333.png">

Error:
[POST https://www.0crat.com/rfp-pay] failed in 9ms: 404

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@alayor[/z](https://www.0crat.com/u/alayor) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@alayor fixed in https://github.com/zerocracy/farm/commit/8a3421413aaaa7c16fd0ed2527b8e76014070714 Please, try again

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
