### ISSUE TITLE
Policy does not mention that ARC can assign/resign people to/from projects

### ISSUE THREAD

**Issue by llorllale** [zerocracy/zerocracy.github.io#14]
If the ARC can assign/resign people people from projects, the policy should say so, similar to how it documents this ability for POs in [13](http://www.zerocracy.com/policy.html#13).

Currently it just documents that ARC can assign/resign people from *jobs*, not projects.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@llorllale fixed in 2456f17 thanks

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
