### ISSUE TITLE
Mentor graduation fee is missed in policy

### ISSUE THREAD

**Issue by g4s8** [zerocracy/zerocracy.github.io#19]
Policy doesn't have information about mentor graduation fee as in https://github.com/zerocracy/farm/issues/1242
It supposed to be 120 minutes. Also this value should be accessible via id.

**Comment by yegor256** [comment]
@g4s8 see e762211

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zerocracy/zerocracy.github.io#19` is not assigned, can't get performer
