### ISSUE TITLE
Yoti bug with iPhone camera

### ISSUE THREAD

**Issue by ledestin** [zerocracy/zerocracy.github.io#20]
It's important to use Yoti's own scanner, not iPhone's camera to share identity. There's an error every time I use iPhone camera (that runs Yoti).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@ledestin[/z](https://www.0crat.com/u/ledestin) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@ledestin Yoti is external service, we don't control theirs apps. You can submit tickets related to Yoti here: https://github.com/getyoti/

**Comment by ledestin** [comment]
@g4s8 well, you might get more manual identification requests because of that. Up to you.

**Comment by yegor256** [comment]
@ledestin this should be reported to https://github.com/zerocracy/farm

**Comment by 0crat** [comment]
Job `gh:zerocracy/zerocracy.github.io#20` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
