### ISSUE TITLE
ARC rewards are missed in policy

### ISSUE THREAD

**Issue by g4s8** [zerocracy/zerocracy.github.io#23]
There are no information in policy about ARC rewards as requested in https://github.com/zerocracy/farm/issues/1269

**Comment by g4s8** [comment]
@yegor256 please update the policy with this comment: https://github.com/zerocracy/farm/issues/1269#issuecomment-402054891 and some numbers for rewards

**Comment by yegor256** [comment]
@g4s8 see 3040144

**Comment by g4s8** [comment]
@yegor256 thanks
