### ISSUE TITLE
0crat bot doesn't accept Paypal emails on Slack

### ISSUE THREAD

**Issue by mgrassotti** [zerocracy/zerocracy.github.io#24]
Hi there,

I tried to type this on Slack:
```
wallet paypal <email>
```
0crat answered: 
```
Email address is not valid: `<email>`
```
I tried also another email address, registered with Paypal, same answer.
I checked for typos in the emails. 
It worked on Telegram at the first time.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@mgrassotti[/z](https://www.0crat.com/u/mgrassotti) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:zerocracy/zerocracy.github.io#24` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
