### ISSUE TITLE
REV tasks should get bigger bonus for good quality than DEV tasks

### ISSUE THREAD

**Issue by krzyk** [zerocracy/zerocracy.github.io#25]
After recent changes there is a constant 8% bonus for good quality of all tasks (DEV and REV) instead of constant 5mins. So the bonus now is 2.4min for DEV task and 1.2min for REV task.

REV task was hit the most 5min -> 1.2 min.

Because getting a good quality DEV task is very easy (there are much less restrictions - most common mistake is not addressing comments), but doing the same for REV tasks is harder. One has to find 3 bugs in the code that are not cosmetic.

As such I think that bonus for good REV task should be bigger - e.g. like previously ~32%~ 33% (which would be ~5mins).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@yegor256 please, look at this issue, what do you think?

**Comment by yegor256** [comment]
@g4s8 good point, I agree

**Comment by g4s8** [comment]
@yegor256 please see #26

**Comment by yegor256** [comment]
@g4s8 #26 merged

**Comment by g4s8** [comment]
@krzyk new bonus value was merged in #26, close please

**Comment by 0crat** [comment]
Job `gh:zerocracy/zerocracy.github.io#25` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
