### ISSUE TITLE
Add this repo to Zerocracy project at 0crat

### ISSUE THREAD

**Issue by t-izbassar** [zerocracy/zerocracy.github.io#3]
#This repository is a part of Zerocracy project and should be added to the 0crat. As @yegor256 asked to have QA rules proposals here: they are definitely improve the 0crat project. Or if you don't want to add this repo to 0crat - then you should state that here are only cosmetic issues, not the ones that affects the overall 0crat behavior an behavior of the people involved on that. (I'm talking about [this change](https://github.com/zerocracy/datum/issues/300) )

**Comment by 0crat** [comment]
@t-izbassar[/z](https://www.0crat.com/u/t-izbassar) I'm not managing this repo, remove the [webhook](https://github.com/zerocracy/zerocracy.github.io/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11) //cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@t-izbassar fixed thanks

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.jcabi.xml.XSLDocument[400] java.lang.IllegalArgumentException: Failed to transform by net.sf.saxon.TransformerFactoryImpl: [Job name "gh:zerocracy/zerocracy.github.io#3" is not valid, Processing terminated by xsl:message at line 27 in file:///; SystemID: file:///; Line#: 27; Column#: 6]
net.sf.saxon.expr.instruct.Message[223] net.sf.saxon.expr.instruct.TerminationException: Processing terminated by xsl:message at line 27 in file:///
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)
