### ISSUE TITLE
TOC - "Fork me on Github" link broken

### ISSUE THREAD

**Issue by mgrassotti** [zerocracy/zerocracy.github.io#30]
The link "Fork me on Github" on http://www.zerocracy.com/toc.html is broken.
<img width="413" alt="schermata 2018-07-03 alle 11 20 15" src="https://user-images.githubusercontent.com/6908677/42211451-f0d4f6d6-7eb3-11e8-8761-5ce2490966b4.png">

It redirects to a Github 404 page.
<img width="805" alt="schermata 2018-07-03 alle 11 20 23" src="https://user-images.githubusercontent.com/6908677/42211465-f5924cc8-7eb3-11e8-88f8-578aee96a154.png">

The `href` @ `zerocracy.github.io/_layouts/page.html:5` should be probably updated to `https://github.com/zerocracy/zerocracy.github.io/issues`?

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@mgrassotti[/z](https://www.0crat.com/u/mgrassotti) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:zerocracy/zerocracy.github.io#30` is not assigned, can't get performer
