### ISSUE TITLE
Job time budget is in contrast with the principle "pay for deliverables"

### ISSUE THREAD

**Issue by mgrassotti** [zerocracy/zerocracy.github.io#31]
[§4 Fixed Budget](http://www.zerocracy.com/policy.html#4) states:  _Each job has a **fixed budget in minutes**, which will be multiplied by your hourly rate and paid to you when the job is completed._

I think **this is contrast with the general principle "pay for deliverables, not for time"**  (https://www.yegor256.com/2015/07/21/hourly-pay-modern-slavery.html)

If we assume the actual completion time is not important for each task (as it will be paid the same), **why are we budgeting jobs in minutes?**
I think budgeting for each job should be decoupled from its completion time and from the experience and role of the person who will complete it, and have instead a **budget in $**:

- each developer will evaluate if the budget if enough for him to complete the job.
- each developer can add new _todos_ or _tasks_ if he feels the budget cannot include all the work needed, during its completion, as foreseen in Puzzle Driven Development

We could say that a higher rate for senior developers is fair, because they are providing better solutions and code, maybe even faster. But in reality, **with code reviews, we are trying to achieve the maximum possible quality in each piece of code**. So it is more like senior developers are delegating the actual code production to other developers, but the value of final code is required to be the same. It just probably will take more time if it is delegated to a junior developer. 

Let say it a job takes actually 2 hours in total (including coding and code reviews).
But should it be paid, let's say, 8$ (16$/hour * 30 minutes budget) in one case and 32$ (64$/hour * 30 minutes budget) in the other, while the final code quality is the same?

Shouldn't it be better to **set a 32$ budget for the job?**

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@mgrassotti[/z](https://www.0crat.com/u/mgrassotti) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:zerocracy/zerocracy.github.io#31` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
