### ISSUE TITLE
Policy XML is broken

### ISSUE THREAD

**Issue by carlosmiranda** [zerocracy/zerocracy.github.io#49]
Policy XML is broken, this is causing Zerocracy to break: https://github.com/zerocracy/farm/issues/1089#issuecomment-408810630

The problem is this `meta` tag:

https://github.com/zerocracy/zerocracy.github.io/commit/9d9f87d2cef5558dc50a3de0ba51e443a0cd90a4#diff-2c19d9859b055d0302043d0fa2833e3fR14

**Comment by carlosmiranda** [comment]
@yegor256 @g4s8 please fix this ASAP, this is breaking everything

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by yegor256** [comment]
@carlosmiranda @g4s8 fixed

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zerocracy/zerocracy.github.io#49` is not assigned, can't get performer
