### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by Glusk2** [zerocracy/zerocracy.github.io#5]
In [policy.md](https://github.com/zerocracy/zerocracy.github.io/blob/9f41d7bd140a4f315c60546042736ca349fbe629/pages/policy.md):
> - We are broken (just kidding)

Someone probably meant **broke** (without money) as opposed to **broken** (not functional) but I could be wrong.

**Comment by 0crat** [comment]
@glusk2[/z](https://www.0crat.com/u/glusk2) I'm not managing this repo, remove the [webhook](https://github.com/zerocracy/zerocracy.github.io/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11) //cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@Glusk2 fixed, thanks!

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.jcabi.xml.XSLDocument[400] java.lang.IllegalArgumentException: Failed to transform by net.sf.saxon.TransformerFactoryImpl: [Job name "gh:zerocracy/zerocracy.github.io#5" is not valid, Processing terminated by xsl:message at line 27 in file:///; SystemID: file:///; Line#: 27; Column#: 6]
net.sf.saxon.expr.instruct.Message[223] net.sf.saxon.expr.instruct.TerminationException: Processing terminated by xsl:message at line 27 in file:///
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)
