### ISSUE TITLE
Resumes and invitation inconsisencies

### ISSUE THREAD

**Issue by krzyk** [zerocracy/zerocracy.github.io#54]
Paragraph 1 states that a resume reviewer can deny or invite a user, and he gets +32 points for both.
But in the same paragraph it is stated that inviting a user is a -128 points. So a user that invites gets +32 - 128 = -96 points. So what's the point of getting those +32 points if it is later on neglected by taking back 128 points?

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@yegor256 please look at this issue, looks like we didn't discuss what to do with old reputation value, I think we should remove it and use only `+32` on invite, right?

**Comment by yegor256** [comment]
@g4s8 yes, you are right, let's just use +32 on invite.

**Comment by g4s8** [comment]
@krzyk @yegor256 please see #59

**Comment by krzyk** [comment]
@g4s8 thanks

**Comment by 0crat** [comment]
Job `gh:zerocracy/zerocracy.github.io#54` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
