### ISSUE TITLE
Broken HTML layout on https://www.0crat.com/board

### ISSUE THREAD

**Issue by cucumber007** [zerocracy/zerocracy.github.io#56]
Chrome 68.0.3440.106
![sdfsd](https://user-images.githubusercontent.com/6491358/45221141-3acce300-b2b9-11e8-846f-ba237e22422b.PNG)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@cucumber007[/z](https://www.0crat.com/u/cucumber007) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@ledestin this should be reported to https://github.com/zerocracy/farm

**Comment by 0crat** [comment]
Job `gh:zerocracy/zerocracy.github.io#56` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
