### ISSUE TITLE
FAQ for a new project

### ISSUE THREAD

**Issue by emilianodellacasa** [zerocracy/zerocracy.github.io#62]
Today I added a new project to Zerocracy as a PO to try the onboarding process.

Mainly, I found one main issue: [here](https://www.zerocracy.com/policy.html#17) it says that the PO should `link` the github project using a command on Slack, however this is not possible until the ARC `bootstrap` the project.

I find it pretty confusing actually and maybe the whole onboarding process should be revised, however for the moment it would be enough to clearly state that necessary passage on the FAQ.

Also, it is not specified in the FAQ that 0crat bot has to be added to the project as a collaborator

**Comment by g4s8** [comment]
@0crat assign me

**Comment by g4s8** [comment]
@emilianodellacasa please look at #64 
does it clear or you need more details?

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/zerocracy.github.io/issues/62#issuecomment-459025469))

@g4s8 @g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#62](https://github.com/zerocracy/zerocracy.github.io/issues/62), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by emilianodellacasa** [comment]
@g4s8 I think it's enough

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by g4s8** [comment]
@emilianodellacasa PR #64 was merged, you can check the FAQ on https://www.zerocracy.com/pfaq.html, can we close then?

**Comment by emilianodellacasa** [comment]
@g4s8 thanks

**Comment by 0crat** [comment]
Job [#62](https://github.com/zerocracy/zerocracy.github.io/issues/62) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#62](https://github.com/zerocracy/zerocracy.github.io/issues/62) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
