### ISSUE TITLE
Negative point from mistake of students is sometime unfair

### ISSUE THREAD

**Issue by victornoel** [zerocracy/zerocracy.github.io#63]
Basically, one of my student is now ARC and is assigning job manually for some reasons (most certainly for good reasons ;).

Everytime this happens, I get -15 or -20 points (5 for assigning to creator, 15 for manually assigning).

I believe there are mistakes that make sense to impact the mentor, but some others, like those ones, doesn't seem to.

Also, in terms of coherence, there are things that are quite unfair:
1. Balance between mistakes and tuition
  - if my student does something good, I get 8% of what he does
  - if my student does something bad, I get 100% of what he does
2. Lately I loose more than I gain even though I'm working positively for the system
  - a REV job give me 15 points
  - my student manually assigning a job give me -20 points

So:
1. I wonder if we shouldn't restrict mistakes to some actions, not all
2. Maybe we should rethink the value of mistake (not 100%) for the mentor

@yegor256 WDYT?

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by victornoel** [comment]
@g4s8 @yegor256 ping?

**Comment by g4s8** [comment]
@victornoel 
>    if my student does something good, I get 8% of what he does
>    if my student does something bad, I get 100% of what he does

you get 8% of real cash and 100% of reputation points, it's not equal.

> my student manually assigning a job give me -20 points

you can get -20 points only if student assign a task to himself, for manual ticket handling you get only -5 points.

You can always break up with student and use it as a lever of pressure, if you receive only negative points and not cash bonuses, just use `breakup username`. I think you need to find the balance between the bonuses and negative points, so if student is not profitable for you then breakup.

**Comment by victornoel** [comment]
@g4s8 ok, if you think it's acceptable like this, I'm good with it. Let's close this!

**Comment by 0crat** [comment]
Job `gh:zerocracy/zerocracy.github.io#63` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
