### ISSUE TITLE
WBS link leads to blank page

### ISSUE THREAD

**Issue by alex-semenyuk** [zerocracy/zerocracy.github.io#65]
https://www.0crat.com/u/{user-name}/wbs leads to blank page

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@alex-semenyuk[/z](https://www.0crat.com/u/alex-semenyuk) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@alex-semenyuk this should be reported to https://github.com/zerocracy/farm

**Comment by 0crat** [comment]
Job `gh:zerocracy/zerocracy.github.io#65` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
