### ISSUE TITLE
How to set/unset "sandbox" status and who does it?

### ISSUE THREAD

**Issue by llorllale** [zerocracy/zerocracy.github.io#67]
Who (ARC,PO) can set sandbox status on a project and how is it done? The policy does not explain.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@llorllale it's not possible now, Zerocracy has a fixed set of sandbox projects.

**Comment by llorllale** [comment]
@g4s8 oh, ok. Thanks.

**Comment by 0crat** [comment]
Job `gh:zerocracy/zerocracy.github.io#67` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
