### ISSUE TITLE
0crat bot doesn't post a message on GitHub about assigning

### ISSUE THREAD

**Issue by SharplEr** [zerocracy/zerocracy.github.io#7]
I have [this issue](https://github.com/yegor256/cactoos/issues/638) in my `Agenda` on [0crat site](https://www.0crat.com).
I also got a message from Telegram bot about it.

But the GitHub bot doesn't post any message about assigning.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@ledestin this should be reported to https://github.com/zerocracy/farm

**Comment by 0crat** [comment]
Job `gh:zerocracy/zerocracy.github.io#7` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
