### ISSUE TITLE
90 days rule explanation required

### ISSUE THREAD

**Issue by t-izbassar** [zerocracy/zerocracy.github.io#8]
I don't quite understand how this rule works. As for now it seems like they just vanished in 1 day all at once. So do we have some rolling seasons of reputation? For example if I earned 300 points throughout the winter they will be deducted to 0 points at the 1st of March? If so, what are the seasons and how are they calculated?

Or every award leave 90 days and they are deducted more smoothly? I actually would prefer to have it like that. So that if one person earned 300 points throughout the month he will loose reputation smoothly in next 90 days as every award will have it's own expiration date. But I can have a look at reputation and match it to current performance. That's not possible with seasoned style as in the start of new season all members will have 0 reputation.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@t-izbassar yes, it's rolling. This means that we delete your awards every hour, if they are too old. We just didn't have that functionality implemented, that's why no awards were being deleted. Now the feature works and checks your awards every hour.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
