### ISSUE TITLE
Specify that there are applicants examiners with the special right to eject resumes being assigned for the examination

### ISSUE THREAD

**Issue by denis-konovalyenko** [zerocracy/zerocracy.github.io#80]
Specify that there are applicants examiners with the special right to eject resumes being assigned already for the examination.

[This](https://github.com/zerocracy/farm/issues/1992) is the exact situation which might happen out of a sadden. And [this](https://github.com/zerocracy/farm/issues/1993) is a proposal to improve this on the software level.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@denis-konovalyenko please see #81

**Comment by victornoel** [comment]
@denis-konovalyenko I think you should close this issue now.

**Comment by denis-konovalyenko** [comment]
@victornoel , thanks for keeping an eye on this.

**Comment by 0crat** [comment]
Job `gh:zerocracy/zerocracy.github.io#80` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
