### ISSUE TITLE
Specify when a performer can get 50% of their hourly rate for a job

### ISSUE THREAD

**Issue by denis-konovalyenko** [zerocracy/zerocracy.github.io#82]
It is not clear when a performer can get 50% of their hourly rate for a job.

E.g.:

 0crat commented 6 days ago:
>    @0crat status (here)

@denis-konovalyenko This is what I know about this job in GFV03LPPY, as in §32:

    The job #7 is in scope for 11days
    The role is DEV
    The job is assigned to @denis-konovalyenko/z for 11days
    There is a monetary reward attached
    @denis-konovalyenko/z will get 50% of their hourly rate for this job
    The job has an impediment
    The budget is 30 minutes/points
    These users are banned and won't be assigned:
        @paulodamaso/z: This user reported the ticket
    Job footprint (restricted area)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@denis-konovalyenko see:
> The budget is 30 minutes/points

it means that you will get 50% of hourly rate for this job (50% of hourly rate = payment for 30 minutes).

**Comment by denis-konovalyenko** [comment]
@g4s8 , ah, it was not that obvious to assume and I understood that I would be paid for 15 minutes only:
```
The budget is 30 minutes/points
```
and
```
@denis-konovalyenko/z will get 50% of their hourly rate for this job
```

Wouldn't it be better to have just the "_The budget is 30 minutes/points_" message only or make them in one line at least: "_The budget is 30 minutes/points (@denis-konovalyenko/z will get 50% of their hourly rate for this job)_"?

By the way, is it possible to get 100%, 200% of someone hourly rate for a 30 minutes job or the job budget is boosted proportionally?

**Comment by denis-konovalyenko** [comment]
@g4s8 , the related issue[ #1994](https://github.com/zerocracy/farm/issues/1994) has been submitted to move this discussion there.

Thanks for taking a look at this again!

**Comment by 0crat** [comment]
Job `gh:zerocracy/zerocracy.github.io#82` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
