### ISSUE TITLE
A counter of amount of money earned on the platform during a period of time 

### ISSUE THREAD

**Issue by Sammers21** [zerocracy/zerocracy.github.io#84]
Having a counter, which would count the amount of money earned on the platform today/last week/last month would be awesome.

This also would attract people to work on the platform.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@sammers21[/z](https://www.0crat.com/u/sammers21) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@Sammers21 we already have KPI metrics, but it's visible only to PMO users, @yegor256 maybe we can make it public, e.g. accessible via web page?

**Comment by yegor256** [comment]
@g4s8 yes, would be great, I agree

**Comment by g4s8** [comment]
@Sammers21 please move this ticket to https://github.com/zerocracy/farm/issues and close this one

**Comment by 0crat** [comment]
Job `gh:zerocracy/zerocracy.github.io#84` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
