### ISSUE TITLE
Disencourage reputation farming while on vacation and/or without assigned jobs?

### ISSUE THREAD

**Issue by Protagores** [zerocracy/zerocracy.github.io#86]
Currently the Policy does not discriminate between the users who are being assigned jobs and who are not, in regards to their reputation rewards. I see a few problems with this, namely:

- Such users without assigned jobs have the ‘luxury’ of being selective with the tasks they want to work on, and don’t have to deal with reputation risks associated with e.g. not delivering on time. This is unfair in relation to other users who are being assigned jobs and deal with such risks routinely.
- Students may cheat the graduation process without having to learn to fit into project workflow and to deliver results on time properly, just by earning points required by [§33](https://www.zerocracy.com/policy.html#33) and [§43](https://www.zerocracy.com/policy.html#43) from vacation mode, or outside of being assigned to a project. This would be bound to result in ‘real’ projects having to deal with unmanageable members who waste time on jobs which could be assigned to more suitable members.

I propose adding a clause that would reduce (e.g. halve) the amount of points awarded to users on vacation and/or not having any assigned tasks for whatever ‘positive’ activity they do on the platform while so. However, if an user does have assigned jobs and is not on vacation, the amount of points rewarded for extra activity not associated with their current jobs would remain as usual.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@protagores[/z](https://www.0crat.com/u/protagores) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@Protagores sorry, Id didn't get the point. The're no difference between points for "on vacation" users and "not on vacation" users, user can get reputation only in few cases: for bug reporting (15 min), for job (30 min for DEV task and 15 for REV), for QA review (4 min) and some ARC bonuses. 

> Such users without assigned jobs have the ‘luxury’ of being selective with the tasks they want to work on, and don’t have to deal with reputation risks associated with e.g. not delivering on time. This is unfair in relation to other users who are being assigned jobs and deal with such risks routinely.

User can't select tasks to work, if such user completed a job, he/she won't get any reputation for that, user can earn reputation only if job was closed and user was a performer of that job.

> Students may cheat the graduation process without having to learn to fit into project workflow and to deliver results on time properly, just by earning points required by §33 and §43 from vacation mode, or outside of being assigned to a project. This would be bound to result in ‘real’ projects having to deal with unmanageable members who waste time on jobs which could be assigned to more suitable members.

I can't see how students may cheat, please explain with more details.

**Comment by Protagores** [comment]
> User can't select tasks to work, if such user completed a job, he/she won't get any reputation for that, user can earn reputation only if job was closed and user was a performer of that job.

In that case, would it mean that [§48](https://www.zerocracy.com/policy.html#48) effectively applies only to bug reporting?

> I can't see how students may cheat, please explain with more details.

My point was, if the students could earn points for closing tasks which were not assigned to them, they could graduate without having to go through the normal process of job assignment and the Ten Days Rule.

**Comment by g4s8** [comment]
@Protagores 
> In that case, would it mean that §48 effectively applies only to bug reporting?

yes, if user doesn't belong to a project, he/she can earn points only for bug reporting (and if bug was accepted as valid).

**Comment by 0crat** [comment]
Job `gh:zerocracy/zerocracy.github.io#86` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
