### ISSUE TITLE
ARC not visible in project board

### ISSUE THREAD

**Issue by scristalli** [zerocracy/zerocracy.github.io#95]
I want to write to ARC of my project in an issue, but ARC is not visible in the project board so I cannot know who he/she is.
Piece of output from the board page, as you can see ARC's `<td>` is empty:
```
<tr style="opacity:0.5;">
	<td><a href="/p/C3NDPUA8L"><code>C3NDPUA8L</code></a><span style="display:block;font-size:0.8em;line-height:1em;"><span style="color:darkred;" title="The project has no funds, you will work for free">no funds</span></span></td>
	<td>Zerocracy</td>
	<td></td>
	<td><a href="https://github.com/zerocracy/farm">zerocracy/farm</a>, <a href="https://github.com/zerocracy/datum">zerocracy/datum</a>, <a href="https://github.com/zerocracy/zerocracy.github.io">zerocracy/zerocracy.github.io</a></td>
	<td>Java, CSS, Shell, TeX, XSLT, HTML, Groovy, Ruby</td>
	<td style="text-align:right;">13</td>
	<td style="text-align:right;"><span style="text-decoration:line-through;color:darkred;">27/217</span><a href="#2"><sup>2</sup></a></td>
</tr>
```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@scristalli[/z](https://www.0crat.com/u/scristalli) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by scristalli** [comment]
I've just seen that the architect is visible from the project's page (so my problem is gone), but the column in the board remains empty.

**Comment by g4s8** [comment]
@scristalli please move this bug here: https://github.com/zerocracy/farm/issues
this repository is used for policy, terms and other pages issues.

**Comment by scristalli** [comment]
Done, moved [here](https://github.com/zerocracy/farm/issues/2069). I actually checked first because I was unsure, I opened here because I saw #56.

**Comment by g4s8** [comment]
@scristalli thanks, #56 also was moved to farm repo: https://github.com/zerocracy/zerocracy.github.io/issues/56#issuecomment-478227306

**Comment by 0crat** [comment]
Job `gh:zerocracy/zerocracy.github.io#95` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
