### ISSUE TITLE
Add another Quality bad condition to the policy

### ISSUE THREAD

**Issue by sereshqua** [zerocracy/zerocracy.github.io#96]
Following Victor Noël's suggestion in TG channel:

When someone does a job, but then quit the project before it is closed and is not getting the points. Then the job is assigned to someone else and then finally the job is closed. Then the QA should give `quality bad` verdict in this situation.

Currently, it is written in policy that:

```
The quality of a job is “bad” if any of the following happens (these violations we can’t forgive):

 - The code reviewer didn’t find any issues in the source code changes of a pull request and just accepted it;
 - The job is closed without a solution provided.
```

It's not enough clear that the performer didn't provide a solution and quality should be bad. And the policy says nothing about performer, thus I think that it (policy) should be clarified.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@sereshqua please see #97

**Comment by sereshqua** [comment]
@g4s8 checked, looks good

just out of curiosity, should not this issue be registered as a bug as well? (get scope label, get 15 points and etc) or policy issues are not included in bug reporting rule?

**Comment by g4s8** [comment]
@sereshqua usually, we don't add such bugs (to change 1-5 line) to scope, see https://www.zerocracy.com/policy.html#29 And 0crat skip review for small PRs also: https://github.com/zerocracy/zerocracy.github.io/pull/97#issuecomment-499015642

**Comment by g4s8** [comment]
@sereshqua #97 was merged into policy, can we close?

**Comment by 0crat** [comment]
Job `gh:zerocracy/zerocracy.github.io#96` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
